### ISSUE TITLE
browser support?

### ISSUE THREAD

**Issue by qasimalyas** [wouter2203/fuzzy-search#15]
Whats the browser support on this? I reckon that would be worth having in the docs too as its useful information.

Thanks

**Comment by wouter2203** [comment]
It should work on all modern browsers and IE9+.

I'll update the tests later this week to have them tested in real browsers and will add the results to the readme :)

**Comment by wouter2203** [comment]
@qasimalyas Hi, I've added a browser matrix in the readme. You can see in what browsers Fuzzy Search is working perfectly over there :)
