### ISSUE TITLE
searching multiple keys at once

### ISSUE THREAD

**Issue by aaronjensen** [wouter2203/fuzzy-search#31]
It'd be great if it (by default, or with an option) allowed a single search phrase to span multiple keys. For example, with:

`[{name: 'The Adventures of Tom Sawyer', author: 'Mark Twain'}]`

A search with keys `['name', 'author']` for `'tom mark'` would return no results today, but I'd like for it to return the item in the array as a result. 

I'm aware that I can create a compound key, but it'd be great if that were unnecessary. Thanks!

**Comment by wouter2203** [comment]
Wow I'm late to this, sorry!

I think mapping the object and adding a compound key would be easier for this situation, which I don't think is a common problem. Also, adding an option for this would make the plugin more complex.

For example:

```js
// Your data is probably in some kind of variable.
const data = [{ name: 'The Adventures of Tom Sawyer', author: 'Mark Twain' }];

// Run this one liner.
data.forEach(entry => entry.compound = `${entry.name} ${entry.author}`);

// And now we have an extra key in our entries which we can search on: compound.
// [{ name: 'The Adventures of Tom Sawyer', author: 'Mark Twain', compound: 'The Adventures of Tom Sawyer Mark Twain' }]
```

I understand you knew how to solve the problem, but just as demonstration for others searching the issues.

**Comment by aaronjensen** [comment]
@wouter2203 No problem, thanks for the response. We are doing this today. It has one glaring issue, however, while a search for "Twain Sawyer" would return results in your example, a search for "Sawyer Twain" will not. Of course, one could join name+author+name to work around this, but I worry about the impact that would have. 

I totally understand not wanting to make fuzzy-search more complicated, its simplicity is one of the reasons we initially chose it. We may end up moving to one of the more sophisticated packages, but this one has served us well for a while now...

Thanks again!
