### ISSUE TITLE
Not working with empty Arrays

### ISSUE THREAD

**Issue by X-Tender** [wouter2203/fuzzy-search#33]
Is it just me or did this lines somehow didn't make sense.
```javascript
 constructor(haystack = [], keys = [], options = {}) {
    if (haystack.length === 0) {
      throw new Error('We need an array containing the search list');
    }
```
It looks like that it throws the error when the length of the haystack is 0 .. but the default is an empty Array. Also it can happen that the haystack is empty.

wouldn't it be better this way:
```javascript
 constructor(haystack = [], keys = [], options = {}) {
    if (haystack.constructor !== Array) {
      throw new Error('We need an array containing the search list');
    }
```

**Comment by wouter2203** [comment]
Fixed in https://github.com/wouter2203/fuzzy-search/pull/34
