### ISSUE TITLE
Not working with VueJS

### ISSUE THREAD

**Issue by dunklesToast** [wouter2203/fuzzy-search#37]
Whenever I try to import this module into my VueJS / Nuxt Setup I encounter this error: `render function or template not defined in component: anonymous`
If I comment the import out the page renders normally.

Do you have any workaround?

**Comment by wouter2203** [comment]
It seems to work with Vue, it shouldn't conflict with it..

Take a look at: https://codepen.io/anon/pen/gZGBYX?editors=1111

However this isn't done with an `import` since that isn't possible in a codepen.

Could you show me an example of your code, so I can see what the problem is?
