### ISSUE TITLE
Advanced key matching?

### ISSUE THREAD

**Issue by simlu** [wouter2203/fuzzy-search#40]
This project to my understanding does two things: Searching object entries based on keys and then matching and scoring their corresponding values.

I've created a library called [object-scan](https://github.com/blackflux/object-scan), which does solve the first part nicely (there is a lot to it). Would you be interested in a pull request?

When I started I thought object traverse and search was an easy problem. It is not. Hence it might be a good idea not to reinvent the wheel here ;) `objext-scan` is a dependency free package (which would fit with fuzzy-search) and has many, many tests.

Let me know what you think! Cheers, L~

**Comment by wouter2203** [comment]
This project does exactly what you think it does! :)

I’m not sure if this project needs to expand to wildcard match the object keys. Usually, you want to search in specific and known keys. And when that’s not the case, it’s relatively easy to build a new object that has the required keys for searching. Such objects would be even easier to create with your package. 

Therefore, I think I want to leave the package as it is right now. Fuzzy-search is a simple and small project. No need to make it more advanced. But for people that need more complex key matching, your package could be helpful in creating an object that’s searchable with fuzzy-search. So I’m happy to add a disclaimer of some sort in the readme where I’ll link to your package, if that's okay with you.

I’ll close the issue now, but feel free to comment and let me know what you think about the disclaimer for people that like the more advanced stuff!

**Comment by simlu** [comment]
That's very true. One could easily chain object - scan and fuzzy-search. Its a little overhead since keys need to be accessed twice, but in most cases acceptable. 

Feel free to add a note. Object-scan and wildcard/glob matching has been incredibly useful for me, but I'm also not solving standard solutions I think. So this might not be as important for the majority of the users of this project.
