### ISSUE TITLE
In Node 10.x + Typescript using ts-node fuzzy-search fails when new'd

### ISSUE THREAD

**Issue by ktiedt** [wouter2203/fuzzy-search#43]
The output from ts-node REPL after importing the Parser and calling the search routine.

```
 var searcher = new fuzzy_search_1.default(this.registrations, ['name', 'realName', 'email', 'previousEmails', 'regCode'], {
                       ^

TypeError: fuzzy_search_1.default is not a constructor
```

The actual code is:
```
    searchRegistrations(needle: string) {
        const searcher = new FuzzySearch(this.registrations, ['name', 'realName', 'email', 'previousEmails', 'regCode'], {
            caseSensitive: false,
          });

          return searcher.search(needle)
    }
```

I dug around a bit and I can't find anything that I missed... this project looks amazing and was excited to find it. Hope its something simple we missed.

Thanks for the awesome project and the help!

**Comment by ktiedt** [comment]
Turns out switching from:
```
import FuzzySearch from 'fuzzy-search'
to
const FuzzySearch = require('fuzzy-search');

```
worked.

I will leave this open just in case there is something meaningful to this failure.

Thanks again!

**Comment by kmjungersen** [comment]
I had to import as: `import * as FuzzySearch from 'fuzzy-search'; ` to resolve this.  Otherwise the types weren't coming in properly too.

**Comment by wouter2203** [comment]
That shouldn't be necessary, I think the umd (https://webpack.js.org/configuration/output/) template is broken. I'll see if I can check/fix things this week!

**Comment by wouter2203** [comment]
Apparently https://github.com/wouter2203/fuzzy-search/pull/52 also fixes this issue. It's working for me, so I'm closing it.

Feel free to reopen it if the problem persist for you!
