### ISSUE TITLE
Sort field does not work as expected

### ISSUE THREAD

**Issue by charliematters** [wouter2203/fuzzy-search#51]
I'm writing a MIME Type dropdown box and using this for fuzzy searching, and the following code demonstrates that the "sort: true" option isn't pulling the best matches to the top:

```
new FuzzySearch(['application/cdfx+xml', 'application/pdf'], { sort: true }).search('pdf') === 'application/cdfx+xml'
```

Just to be clear, I would expect `application/pdf` to be the first result as it is an exact match

**Comment by wouter2203** [comment]
The sort algorithm wasn't smart enough. When the best match is at the end of the string it would fail. I opened a PR that fixes this and a new version will be released in a few minutes!
